<?php

require_once __DIR__ . '/vendor/autoload.php';

Dotenv\Dotenv::createImmutable(__DIR__)->load();

use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

$connection = new AMQPStreamConnection(
    $_ENV["RABBITMQ_HOST"], 
    $_ENV["RABBITMQ_PORT"], 
    $_ENV["RABBITMQ_USER"], 
    $_ENV["RABBITMQ_PASSWORD"]
);

$channel = $connection->channel();

$channel->exchange_declare(exchange: 'logs', type: 'fanout', auto_delete: false);

// When the method returns, the $queue_name variable contains a random queue name generated by RabbitMQ.
// When the connection that declared it closes, the queue will be deleted because it is declared as exclusive.
list($queue_name, ,) = $channel->queue_declare(queue: "", exclusive: true, auto_delete: false);

// We've already created a fanout exchange and a queue. Now we need to tell the exchange to send messages to our queue.
$channel->queue_bind(queue: $queue_name, exchange: 'logs');

echo " [*] Waiting for logs. To exit press CTRL+C\n";

$callback = function (AMQPMessage $msg) {
    echo ' [x] ', $msg->body, "\n";
};

$channel->basic_consume(queue: $queue_name, no_ack: true, callback: $callback);

while ($channel->is_open()) {
    $channel->wait();
}

$channel->close();
$connection->close();